# Generated by Django 3.1.1 on 2020-09-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primero_numero', models.IntegerField()),
                ('segundo_numero', models.IntegerField()),
                ('operdor', models.TextField()),
            ],
        ),
    ]
