# Generated by Django 3.1.1 on 2020-09-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Binario',
        ),
    ]
